### ISSUE TITLE
Support for more ESLint reporters

### ISSUE THREAD

**Issue by muescha** [vfile/ideas#5]
### Subject of the feature

Support for ESLint Reporter

### Problem

i see that some reporters are written in a way that they "just" wrap eslint reporters (for example [vfile-reporter-pretty](https://github.com/vfile/vfile-reporter-pretty/blob/master/index.js), [vfile-reporter-junit](https://github.com/kellyselden/vfile-reporter-junit/blob/master/index.js))

### Expected behavior

- i should use an eslint reporter without wrapping it (autodetect if it is an eslint reporter)
- or use an new option `--eslint-report`

### Alternatives

- create for an ESLint reporter also an vFile Reporter
- extend `vfile-to-eslint` with an option `reporter=eslint-reporter-name`

**Comment by wooorm** [comment]
Where do you want to support this? in remark-cli (-> unified-args -> unified-engine)?

I don’t think we should do this. We’re different projects. Different goals. Different needs. We capture more information than eslint-reporters understand. Generally, reporters would benefit from being custom made for vfile instead of either wrapping or being an ESLint reporter.

What formatters are you interested in?

**Comment by muescha** [comment]
i would like to use it for `remark-cli`

for my use case there are some eslint reporters i like to try out with a detailed output. but everytime you need an additional reporter to convert it.

maybe it can be solved with a new vfile-reporter-multiple like [eslint-formatter-multiple](https://github.com/halkeye/eslint-formatter-multiple/)?

**Comment by wooorm** [comment]
Yeah maybe! I think this makes the most sense in userland. No need to add support for ESLint formatters, JSHint reporters, and what else exists out there in core.

I definitely think there should be more and better formatters in unified-land, but those can be separate projects, and be tailored for vfile!

@ChristianMurphy, what do you think?

**Comment by ChristianMurphy** [comment]
> for my use case there are some eslint reporters i like to try out with a detailed output
> > What formatters are you interested in?

I'd second this question, what formatter(s) are particularly interesting and/or currently missing for vfile/unified?

> No need to add support for ESLint formatters, JSHint reporters, and what else exists out there in core.
> I definitely think there should be more and better formatters in unified-land, but those can be separate projects, and be tailored for vfile!

I'd second this as well. I'd see this being a plugin/package rather than in core.

> maybe it can be solved with a new vfile-reporter-multiple like eslint-formatter-multiple?

Yep, I'd see this as two pieces
1. an adapter pattern for unified reporter to eslint reporter.
2. a splitter which allows running multiple reporters at once.

Each could be a plugin/package

**Comment by muescha** [comment]
> I'd second this question, what formatter(s) are particularly interesting and/or currently missing for vfile/unified?

no one is missing urgend, but some of them i would try. i like more the reports where i see the lines where are the errors.

after search i seen some fancy ones, which , but i never used them:

- https://www.npmjs.com/package/eslint-formatter-mo
- https://www.npmjs.com/package/eslint-codeframe-formatter
- https://www.npmjs.com/package/eslint-audio-formatter
- https://www.npmjs.com/package/eslint-detailed-reporter
- https://www.npmjs.com/package/eslint-formatter-html-extended
- https://github.com/ViggoV/eslint-overview-formatter
- https://github.com/mhipszki/eslint-formatter-summary
- https://github.com/JamieMason/eslint-formatter-git-log
- https://github.com/sven-piller/eslint-formatter-markdown

and much more can be found here 
- https://eslint.org/docs/user-guide/formatters/

> Yep, I'd see this as two pieces
>
> 1. an adapter pattern for unified reporter to eslint reporter.
> 2. a splitter which allows running multiple reporters at once.

you are right with this pieces, it makes no sense to include it into core

**Comment by muescha** [comment]
appending options to a reporter is a little verbose on command line. 

i would like to config the reporter somehow like the `remark-lint` tools in a `.remarkrc.js` file.

when i try with `.remarkrc.js` then the `settings` goes into the Processor.data space and not in to the `settings` from cli :/

**Comment by ChristianMurphy** [comment]
> i would like to config the reporter somehow like the remark-lint tools in a .remarkrc.js file.

Okay, this isn't a part of vfile, it may be better to discuss this at https://github.com/unifiedjs/unified-engine/issues where the configuration management lives.

> when i try with `.remarkrc.js` then the settings goes into the `Processor.data` space and not in to the `settings` from cli :/

I'm not sure what you mean, both are sent to processor data.
You can see the documentation here: https://github.com/unifiedjs/unified-engine/blob/HEAD/doc/configure.md#settings and here https://github.com/unifiedjs/unified-engine/blob/HEAD/doc/options.md#optionssettings

**Comment by wooorm** [comment]
Indeed, you cannot configure a vfile reporter with `settings` in a configuration file.

Can you show us how long the settings are that you are passing directly?

**Comment by muescha** [comment]
you are right - the `rcfiles` are only for the `--use` and for the `--settings` parts of the cli ... somehow i expected also the `report` can be setup there.

> Can you show us how long the settings are that you are passing directly?

if i like to join one ore more reporters with `"a splitter which allows running multiple reporters at once."` then it would better to have a settings file instead of config them via command line. 

but i guess then the "reporter-splitter" can use its own rc file

**Comment by wooorm** [comment]
This issue has now gone one to be more of a list of ideas. For the original, “supporting more eslint reporters”, I don’t think that makes sense.

vfile is a different project. It has different features. If you’d want, for example, a code frame, in my opinion it’d be better to create a new formatter specifically for vfile. Perhaps inspired by eslint, but new!
